### ISSUE TITLE
Unable to load shared library 'plplot' on Linux

### ISSUE THREAD

**Issue by DiomedesDominguez** [mdfarragher/DSC#1]
After I copy the plplot files in Ubuntu 19.04 x64 with the following command `cp ./runtimes/linux-x64/native/lib* .`, I get the error that the project could load the library
```
~/Dev/LoadingData$ dotnet run
Loading data...
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'plplot' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libplplot: cannot open shared object file: No such file or directory
   at PLplot.Native.mkstrm(Int32& p_strm)
   at PLplot.PLStream..ctor() in C:\projects\plplotnet\PLplotNet\PLStream.cs:line 24
   at LoadingData.Program.Main(String[] args) in ~/Dev/LoadingData/Program.cs:line 29
```

**Comment by DiomedesDominguez** [comment]
I even try to specify the runtime.

![Screenshot from 2019-12-12 21-53-37](https://user-images.githubusercontent.com/4379316/70764272-714fa400-1d2d-11ea-9738-c2cd703c8c2d.png)

**Comment by DiomedesDominguez** [comment]
To resolve this I need it to execute the following:
```
$ sudo apt-get install libplplot16 
$ sudo apt-get install plplot-driver-cairo
$ sudo apt-get install libplplot-dev
```
